# Generated by Django 3.0.6 on 2020-05-16 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200516_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Data Structure and Algorithms', 'Data Structure and Algorithms'), ('Programming Languages', 'Programming Languages'), ('Web Development', 'Web Development')], default='', max_length=30),
        ),
    ]
